on:
  push:
    branches: main

name: gen_io_page

jobs:
  gen_page:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sta523-fa22/sta523-base:latest
    env:
      GITHUB_PAT: ${{ secrets.CR_PAT }}
      API_TOKEN_GITHUB: ${{ secrets.CR_PAT }}
    steps:
     
      - uses: actions/checkout@v2
      
      - name: Install tools
        run: |
          apt update
          apt install -y hugo rsync git wkhtmltopdf
      - name: Install Missing Packages
        run: |
          missing = checklist::missing_pkgs(dir = "static/slides/", recurse=FALSE)
          if (length(missing) > 0)
            install.packages(pkgs = missing)
        shell: Rscript {0}
      - name: Build Site
        run: |
          make all
      
      - name: Clean up
        run: |
          rm -f docs/slides/.gitignore
          rm -f docs/slides/.Rhistory
          rm -rf docs/slides/.Rproj.user
          rm -rf docs/slides/prev_*
          ls -la docs/slides/
      
      - name: Config git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "noreply@github.com"
      
      - name: Clone github.io page
        run: |
          git clone "https://$API_TOKEN_GITHUB@github.com/sta523-fa22/sta523-fa22.github.io.git"

      - name: Sync changes
        run: |
          rsync --recursive --delete --exclude=".*" docs/ sta523-fa22.github.io/

      - name: Commit and push changes
        run: |
          cd sta523-fa22.github.io/
          #git status
          git add .
          git commit -m "Update from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)"
          git status
          git push
          
